### ISSUE TITLE
結果が正しくない（中間駅じゃない）ことがある

### ISSUE THREAD

**Issue by nakanakayama23** [nakanakayama23/uluru#13]
[OKの例]
渋谷-新宿の中間駅→原宿
新宿-高田馬場の中間駅→新大久保

[NGの例]
新宿-東京の中間駅→新宿
新宿-品川の中間駅→大崎
池袋-品川の中間駅→目白

**Comment by ghost** [comment]
現状データが正しく入っていないので、入れ直してから再検討

**Comment by ghost** [comment]
入れ直しました

**Comment by heiwa** [comment]
解決したはずなんで。
